### ISSUE TITLE
www folder

### ISSUE THREAD

**Issue by robmarkcole** [HerrHofrat/hassio-addons#3]
I'm not sure if its an issue with hassio or the way this addon is configured but I am unable to set the `www` folder as the target location to save files. 

https://community.home-assistant.io/t/cant-access-www-directory-with-hass-io/34312

**Comment by HerrHofrat** [comment]
The Motion addon is designed to save the snapshots in the share directory. That's why i only map the share in the docker config file. Why do you want to save them in /config/www?

**Comment by robmarkcole** [comment]
Hi, the use case is to integrate the camera feed intn another instance as in the following thread. 

https://community.home-assistant.io/t/stream-rpi-camera-feed-between-ha-multiple-instances/32243

**Comment by HerrHofrat** [comment]
you can define your one motion.conf and enable the webserver for that.

**Comment by robmarkcole** [comment]
Sure, I will have a go
